### PR TITLE
Bugfix/types should be peers with new yarn lock and gitignore

### PR DESCRIPTION
**Pull request by joshball**
React types must be peer-dependencies along with the libraries.
Also, I think the other types (classnames, prop-types, styled-components) should all be moved to devDependencies. But those didn't break me. yet... ;-) The styled-components seems to be the biggest issue, with the react-native types inside....

### CODE REVIEW

**Comment by joshball** [comment]
BTW, there were a lot of new gitignore types, and i had to delete the yarn lock file as well. I have branches without the gitignore changes if that was incorrect to check that in.

**Comment by jxom** [comment]
Fair call - can we also add `@types/react` & `@types/react-dom` to devDependencies too?

**Comment by joshball** [comment]
You bet. I will add those.

**Comment by joshball** [comment]
And what about the other types? 

    "@types/classnames": "2.2.6",
    "@types/prop-types": "15.5.8",
    "@types/styled-components": "4.1.8",

Should we move those to dev as well?
 
`Reakit `which depends on `styled-components` is looking problematic. As you are probably aware, Styled does not like having multiple instances running:

https://www.styled-components.com/docs/faqs#why-am-i-getting-a-warning-about-several-instances-of-module-on-the-page

But I think that styled (in reakit) really should be a peer? Which would allow you to pass the styled version on to the end user. What do you think? Should we ask reakit to make styled a peer?

Oh, and the first question, do you want me to put those types in dev? ;-)

**Comment by joshball** [comment]
Hey @jxom, so what do you think? Can we get this PR in? And does my comment about about Reakit and styled components make sense?

**Comment by joshball** [comment]
Hey @jxom could you merge this?

**Comment by jxom** [comment]
Sorry about the late reply, I haven't had a chance to test this out on a TS project. I think the changes are OK, let's merge it and see how it goes.

**Pull request merged**
